# API設定ファイル
# J-Quants API関連の設定

# J-Quants API設定
jquants:
  base_url: "https://api.jquants.com/v1"
  timeout: 30  # 秒
  max_retries: 3
  retry_interval: 5  # 秒
  rate_limit: 100  # リクエスト/分
  
  # 認証設定
  auth:
    token_expiry: 3600  # 秒
    refresh_threshold: 300  # 秒
    
  # データ取得設定
  data_fetch:
    batch_size: 100
    max_concurrent: 5
    cache_duration: 3600  # 秒
    
  # エンドポイント設定
  endpoints:
    auth: "/auth/token"
    refresh: "/auth/refresh"
    stock_list: "/listed/info"
    stock_prices: "/prices/daily_quotes"
    stock_financials: "/fins/statements"
    
# 外部API設定
external_apis:
  # 必要に応じて他のAPI設定を追加
  backup_data_source:
    enabled: false
    url: ""
    timeout: 30
