name: Generate Sample Cache Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sample-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Create required directories
      run: |
        mkdir -p logs
        mkdir -p docs/data
        echo "Required directories created"
        
    - name: Generate sample cache data
      run: |
        python generate_sample_cache_data.py
        
    - name: Upload sample data artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sample-cache-data
        path: docs/data/
        
    - name: Commit and push sample data
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/data/
        git diff --staged --quiet || git commit -m "Update sample cache data [skip ci]"
        
        # リモートURLをHTTPSに設定
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        
        # プッシュの実行
        if ! git push origin HEAD:main; then
          echo "Push failed, trying to pull and push again..."
          git pull origin main --rebase
          if ! git push origin HEAD:main; then
            echo "Push failed after retry. Please check repository permissions."
            exit 1
          fi
        fi
