name: Generate Sample Cache Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sample-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate sample cache data
      run: |
        python generate_sample_cache_data.py
        
    - name: Upload sample data artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sample-cache-data
        path: docs/data/
        
    - name: Commit and push sample data
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/data/
        git diff --staged --quiet || git commit -m "Update sample cache data [skip ci]"
        git push
