name: jQuants API Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-jquants-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test jQuants API Authentication
      env:
        JQUANTS_EMAIL: ${{ secrets.JQUANTS_EMAIL }}
        JQUANTS_PASSWORD: ${{ secrets.JQUANTS_PASSWORD }}
        JQUANTS_ID_TOKEN: ${{ secrets.JQUANTS_ID_TOKEN }}
        JQUANTS_REFRESH_TOKEN: ${{ secrets.JQUANTS_REFRESH_TOKEN }}
      run: |
        python scripts/test_jquants_api_comprehensive.py
        
    - name: Test Environment Auth Manager
      run: |
        python core/environment_auth_manager.py
        
    - name: Test Enhanced Auth Manager
      env:
        JQUANTS_EMAIL: ${{ secrets.JQUANTS_EMAIL }}
        JQUANTS_PASSWORD: ${{ secrets.JQUANTS_PASSWORD }}
        JQUANTS_ID_TOKEN: ${{ secrets.JQUANTS_ID_TOKEN }}
        JQUANTS_REFRESH_TOKEN: ${{ secrets.JQUANTS_REFRESH_TOKEN }}
      run: |
        python scripts/jquants_auth_manager_enhanced.py
